### ISSUE TITLE
Fixing puppeteer HTML to PDF conversion

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/report#233]
Hello :wave:

With current version of puppeteer the PDF generation seems to be broken (There is probably parameters to review and maybe also CSS print rules to refactor?)

![image](https://user-images.githubusercontent.com/4438263/213035958-d54bfbc9-5e16-43e5-8763-ac96b8177be4.png)

**Comment by SpeedoMacMuffin** [comment]
Hey @fraxken!
I was looking into the issue, but couldn't find anything wrong with puppeteer itself. Could you specify what is exactly broken (except that pretty obvious red block)?

**Comment by fraxken** [comment]
@SpeedoMacMuffin 

I didn't deeg that much. Here the issue is that the content should take the whole PDF width.

So that's probably an issue with the CSS (something has changed at some point when I upgraded puppeteer itself).

**Comment by fraxken** [comment]
@SpeedoMacMuffin yes other contributors reported having no issue (so I guess that's was only reproducible on my local chrome, I will check).

Do not hesitate if you have ideas to improve things, PR are welcome

**Comment by fraxken** [comment]
Ok I had the issue on one of my computed, re-installing node_modules fixed the issue
