### ISSUE TITLE
Missing labels in charts

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/report#257]
The labels are missing from the charts. There were originally supported when I designed the tool (I used the [datalabels plugin](https://chartjs-plugin-datalabels.netlify.app/) of Chart.js).

![missing labels](https://user-images.githubusercontent.com/4438263/225982558-d86334f0-9552-444d-8fb3-2073fde14e18.png)

Here an example when labels worked
![image](https://user-images.githubusercontent.com/4438263/225983190-dfc2b12b-9131-4cb6-936f-65c6a582fa95.png)

Others examples are available in that old article: https://dev.to/nodesecure/nsecure-security-report-19ln

**Comment by CabdiraxiimAxmed** [comment]
I want to work on it, Please assign to me.

**Comment by CabdiraxiimAxmed** [comment]
*nreport initialize* show me this error */usr/bin/env: ‘node --no-warnings’: No such file or directory*
And more over couldn't figure out how to start the project locally.

**Comment by fraxken** [comment]
@CabdiraxiimAxmed hard to help without much info, maybe an issue with the --no-warnings flag if you'r local env fail to detect it?
