### ISSUE TITLE
PDF report transform the NPM link into mailto

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/report#336]
## Reproduction

Create or update `.nodesecurerc` with this content:

```json
{
  "version": "1.0.0",
  "i18n": "english",
  "strategy": "npm",
  "report": {
    "npm": {
      "organizationPrefix": "@topcli",
      "packages": [
        "prompts",
        "spinner"
      ]
    },
    "git": {
      "organizationUrl": "https://github.com/TopCli",
      "repositories": []
    },
    "theme": "light",
    "includeTransitiveInternal": false,
    "reporters": [
      "html",
      "pdf"
    ],
    "charts": [
      {
        "name": "Extensions",
        "display": true,
        "interpolation": "d3.interpolateRainbow",
        "type": "bar"
      },
      {
        "name": "Licenses",
        "display": true,
        "interpolation": "d3.interpolateCool",
        "type": "bar"
      },
      {
        "name": "Warnings",
        "display": true,
        "type": "horizontalBar",
        "interpolation": "d3.interpolateInferno"
      },
      {
        "name": "Flags",
        "display": true,
        "type": "horizontalBar",
        "interpolation": "d3.interpolateSinebow"
      }
    ],
    "title": "Default report title",
    "logoUrl": "https://avatars0.githubusercontent.com/u/29552883?s=200&v=4"
  }
}
```

Run `node . execute`.

It will generate 2 files:
- `/reports/Default report title.html`
- `/reports/Default report title.pdf`

Open both files and go to **Transitive Dependencies**
![image](https://github.com/NodeSecure/report/assets/39910767/9c92f9f6-738f-47ca-a46b-0b1bfee84b53)

Click on `spinner@0.3.4`.

The HTML report open a new tab to https://www.npmjs.com/package/spinner@0.3.4 (don't take care to the 404)
The PDF report try to send a mail.

![image](https://github.com/NodeSecure/report/assets/39910767/fb032885-1e00-4cea-ac40-a71e4a693e46)

## Expected Behavior

The PDF report open https://www.npmjs.com/package/spinner@0.3.4 like the HTML one.

**Comment by lilleeleex** [comment]
Hi could you assign me this issue plz ?
I start a PR

**Comment by lilleeleex** [comment]
Hi, even if the issue is global, here is a proposition at least on the transitive deps. I stuck to CSS styles. I'm only interested in npm stats for the moment but I imagine it's the same for gits stats? Otherwise rendering the pdf in the browser does not open a new tab, I believe that these are rules specific to browsers but I would like your opinion.
