### ISSUE TITLE
Remove isomorphic-git dependency and use a Child proc

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/report#367]
We introduce isomorphic-git just for running a git clone command (that's quite a lot of packages). We probably need to replace that with a simple child proc instead

**Comment by PierreDemailly** [comment]
I think we can use `scanner.from` instead of clone + `scanner.cwd`
Wdyt @fraxken ? Am i missing something ?

**Comment by fraxken** [comment]
@PierreDemailly No because from require that the spec exist in the registry. The goal is to clone and analyze git projects with no relation to the registry.

**Comment by fraxken** [comment]
Or I'm missing something myself lol

**Comment by orlando1108** [comment]
Hi, can you asssign me on that issue please?
