### ISSUE TITLE
Add CLI argument to dump data before HTML report

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/report#375]
It would be useful to have a new CLI argument in execute command

```
$ nreport execute --debug
```

This would enable futher logging (in future PR) and would dump the data and report configuration (in the local storage) before HTML/PDF generation.

Why do we need this you may ask! Because in many situations when developing we need a way to check what's wrong with the data. We sometimes also need to dump it to be able to re-generate a preview with the same datasets (that's exactly what I did to build the preview script).

**Comment by orlando1108** [comment]
it seems to be clear for me, can you assign me on it please ?
